// GENERATED by tools/emit-dart-schema.mjs — do not edit.
//
// The schema lives in app/core/store/schema.js, which the 1.x app imports in a
// browser where there is no filesystem to read a .sql file from. This is that
// schema, emitted for Dart and already split into statements by the splitter
// the shell uses. A test regenerates it and fails if it has drifted, because
// 2.x opens the database 1.x wrote and they have to be the same schema.

/// Every statement of the schema, in order, ready to run one at a time.
const List<String> schemaStatements = [
  r"""
PRAGMA journal_mode = WAL;
""",
  r"""
CREATE TABLE IF NOT EXISTS works (
  work_id        TEXT PRIMARY KEY,
  title          TEXT,
  authors        TEXT,
  summary        TEXT,
  rating         TEXT,
  language       TEXT,
  published      TEXT,
  updated        TEXT,
  downloaded_at  TEXT,
  complete       INTEGER,
  words          INTEGER,
  chapter_count  INTEGER,
  chapters_planned INTEGER,
  updated_at     INTEGER,
  skin_css       TEXT,
  skin_hash      TEXT,
  end_notes_html TEXT,
  source         TEXT,
  source_file    TEXT,
  fetched_at     TEXT,
  in_bookmarks   INTEGER DEFAULT 0,
  rec            INTEGER DEFAULT 0,
  in_history     INTEGER DEFAULT 0,
  bookmarked_at  TEXT,
  last_visited   TEXT,
  visits         INTEGER,
  visits_synced_at TEXT,
  kudos_given    INTEGER DEFAULT 0,
  has_text       INTEGER DEFAULT 0,
  kudos          INTEGER,
  bookmark_count INTEGER,
  hits           INTEGER,
  hidden         INTEGER DEFAULT 0
);
""",
  r"""
CREATE TABLE IF NOT EXISTS tags (
  work_id TEXT NOT NULL,
  kind    TEXT NOT NULL,
  name    TEXT NOT NULL,
  PRIMARY KEY (work_id, kind, name)
) WITHOUT ROWID;
""",
  r"""
CREATE INDEX IF NOT EXISTS tags_by_name ON tags(kind, name);
""",
  r"""
CREATE TABLE IF NOT EXISTS chapters (
  id       INTEGER PRIMARY KEY,
  work_id  TEXT NOT NULL,
  number   INTEGER NOT NULL,
  title    TEXT,
  html     TEXT,
  text     TEXT,
  words    INTEGER,
  content_hash TEXT,
  UNIQUE (work_id, number)
);
""",
  r"""
CREATE INDEX IF NOT EXISTS chapters_by_work ON chapters(work_id, number);
""",
  r"""
CREATE VIRTUAL TABLE IF NOT EXISTS chapter_fts USING fts4(
  content='chapters', text, tokenize=unicode61
);
""",
  r"""
CREATE VIRTUAL TABLE IF NOT EXISTS work_fts USING fts4(
  work_id, title, authors, summary, tags, tokenize=unicode61
);
""",
  r"""
CREATE TABLE IF NOT EXISTS chapter_versions (
  id          INTEGER PRIMARY KEY,
  work_id     TEXT NOT NULL,
  number      INTEGER NOT NULL,
  title       TEXT,
  html        TEXT,
  text        TEXT,
  words       INTEGER,
  content_hash TEXT,
  reason      TEXT,
  archived_at TEXT
);
""",
  r"""
CREATE INDEX IF NOT EXISTS chapter_versions_by_work ON chapter_versions(work_id, number, archived_at);
""",
  r"""
CREATE TABLE IF NOT EXISTS skin_versions (
  id          INTEGER PRIMARY KEY,
  work_id     TEXT NOT NULL,
  skin_css    TEXT,
  skin_hash   TEXT,
  archived_at TEXT
);
""",
  r"""
CREATE INDEX IF NOT EXISTS skin_versions_by_work ON skin_versions(work_id, archived_at);
""",
  r"""
CREATE TABLE IF NOT EXISTS images (
  work_id   TEXT NOT NULL,
  url       TEXT NOT NULL,
  sha256    TEXT,
  mime      TEXT,
  bytes     BLOB,
  status    TEXT,
  fetched_at TEXT,
  PRIMARY KEY (work_id, url)
) WITHOUT ROWID;
""",
  r"""
CREATE TABLE IF NOT EXISTS reading (
  work_id        TEXT PRIMARY KEY,
  chapter        INTEGER,
  offset         REAL,
  chapters_read  INTEGER,
  completed_before INTEGER DEFAULT 0,
  chapter_count  INTEGER,
  marked_later   INTEGER DEFAULT 0,
  imported_from  TEXT,
  updated_at     TEXT,
  opened_at      TEXT
);
""",
  r"""
CREATE TABLE IF NOT EXISTS deleted (
  work_id TEXT PRIMARY KEY,
  title   TEXT,
  at      TEXT
);
""",
  r"""
CREATE TABLE IF NOT EXISTS bookmarked_by (
  person  TEXT NOT NULL,
  work_id TEXT NOT NULL,
  at      TEXT,
  PRIMARY KEY (person, work_id)
) WITHOUT ROWID;
""",
  r"""
CREATE INDEX IF NOT EXISTS bookmarked_by_work ON bookmarked_by(work_id);
""",
  r"""
CREATE TABLE IF NOT EXISTS blocked (
  name TEXT PRIMARY KEY,
  at   TEXT
);
""",
  r"""
CREATE TABLE IF NOT EXISTS reading_visits (
  id TEXT PRIMARY KEY,
  work_id TEXT NOT NULL,
  started_at TEXT NOT NULL
);
""",
  r"""
CREATE INDEX IF NOT EXISTS visits_by_work ON reading_visits(work_id);
""",
  r"""
CREATE TABLE IF NOT EXISTS meta (key TEXT PRIMARY KEY, value TEXT);
""",
];
