/**
 * AO3's HTML into plain objects.
 *
 * AO3's markup is generated by templates, not hand-written, so it is stable
 * and regular enough to read with anchored patterns. Everything here is pure:
 * give it a string, get data back. No fetching, so it can be tested against
 * saved pages and re-run for free when a pattern turns out to be wrong.
 */

import { htmlToText, decodeEntities } from '../epub.js';

const attrOf = (tag, name) => {
  const m = tag?.match(new RegExp(`\\b${name}\\s*=\\s*"([^"]*)"`, 'i'));
  return m ? decodeEntities(m[1]) : null;
};

/** Text of every <a class="tag"> inside a chunk — never comma-splitting. */
function tagsIn(chunk) {
  return [...(chunk || '').matchAll(/<a\b[^>]*class="tag"[^>]*>([\s\S]*?)<\/a>/gi)]
    .map((m) => htmlToText(m[1]))
    .filter(Boolean);
}

const num = (s) => (s == null ? null : Number(String(s).replace(/[^\d]/g, '')) || 0);

/* --------------------------------------------------------------- listings */

/**
 * Split a listing into its blurbs without a DOM.
 *
 * Two shapes exist and they are not interchangeable. A works listing gives
 * <li id="work_123">; a bookmarks listing gives <li id="bookmark_999"
 * class="… work-123 …">, where the work id has moved into the class. Matching
 * only the first shape silently returns nothing for every bookmark page —
 * which is exactly what it did.
 */
export function splitBlurbs(html) {
  return [...html.matchAll(
    /<li[^>]*\bid="(?:work|bookmark)_\d+"[^>]*>[\s\S]*?(?=<li[^>]*\bid="(?:work|bookmark)_\d+"|<\/ol>|$)/gi
  )].map((m) => m[0]);
}

/**
 * One work as it appears in a list of works.
 *
 * The blurb is the crawler's most valuable page: it carries updated_at, so a
 * work already held can be skipped without ever fetching it. That single field
 * is the difference between a sync costing 20 requests and costing 2000.
 */
export function parseBlurb(li) {
  // on a bookmark blurb the element id belongs to the bookmark, and the work
  // id is hiding in the class list as "work-123"
  const workId = li.match(/\bid="work_(\d+)"/i)?.[1]
    ?? li.match(/\bclass="[^"]*\bwork-(\d+)\b/i)?.[1]
    ?? null;
  const bookmarkId = li.match(/\bid="bookmark_(\d+)"/i)?.[1] ?? null;

  // AO3 emits the exact epoch in a comment; the visible "26 Aug 2026" is a
  // lossy rendering of it and would compare wrongly across timezones
  const updatedAt = li.match(/<!--\s*updated_at=(\d+)\s*-->/i)?.[1] ?? null;

  const header = li.match(/<h4 class="heading">([\s\S]*?)<\/h4>/i)?.[1] ?? '';
  const title = htmlToText(header.match(/<a[^>]*href="\/works\/\d+[^"]*"[^>]*>([\s\S]*?)<\/a>/i)?.[1] ?? '') || null;
  const authors = [...header.matchAll(/<a[^>]*rel="author"[^>]*>([\s\S]*?)<\/a>/gi)]
    .map((m) => htmlToText(m[1]));
  const anonymous = /\bclass="[^"]*\banonymous\b/i.test(li) || authors.length === 0;

  // the symbol strip: rating, warnings, category and completion, as classes
  const symbol = (prefix) =>
    li.match(new RegExp(`<span class="${prefix}-([a-z-]+) ${prefix}"[^>]*title="([^"]*)"`, 'i'));
  const rating = symbol('rating')?.[2] ?? null;
  const category = symbol('category')?.[2] ?? null;
  const wip = /class="complete-no iswip"/i.test(li);

  const tagList = li.match(/<ul class="tags commas">([\s\S]*?)<\/ul>/i)?.[1] ?? '';
  const group = (cls) =>
    tagsIn([...tagList.matchAll(new RegExp(`<li class=['"]${cls}['"]>([\\s\\S]*?)<\\/li>`, 'gi'))]
      .map((m) => m[1]).join(''));

  const stat = (name) =>
    li.match(new RegExp(`<dd class="${name}"[^>]*>([\\s\\S]*?)</dd>`, 'i'))?.[1] ?? null;
  const chapters = htmlToText(stat('chapters') ?? '');
  const [done, planned] = chapters.split('/');

  return {
    workId,
    title,
    authors,
    anonymous,
    updatedAt: updatedAt ? Number(updatedAt) : null,
    datetime: htmlToText(li.match(/<p class="datetime">([\s\S]*?)<\/p>/i)?.[1] ?? '') || null,
    fandoms: tagsIn(li.match(/<h5 class="fandoms heading">([\s\S]*?)<\/h5>/i)?.[1] ?? ''),
    rating,
    categories: category ? category.split(/\s*,\s*/) : [],
    complete: !wip,
    warnings: group('warnings'),
    relationships: group('relationships'),
    characters: group('characters'),
    freeform: group('freeforms'),
    summary: htmlToText(li.match(/<blockquote class="userstuff summary">([\s\S]*?)<\/blockquote>/i)?.[1] ?? '') || null,
    language: htmlToText(stat('language') ?? '') || null,
    words: num(htmlToText(stat('words') ?? '')),
    chapters: num(done),
    chaptersPlanned: planned && planned.trim() !== '?' ? num(planned) : null,
    kudos: num(htmlToText(stat('kudos') ?? '')),
    hits: num(htmlToText(stat('hits') ?? '')),
    bookmarkCount: num(htmlToText(stat('bookmarks') ?? '')),
    ...(bookmarkId ? bookmarkInfo(li, bookmarkId) : {}),
    ...readingInfo(li),
  };
}

/**
 * What the bookmark itself records, as opposed to what the work says.
 *
 * The blurb carries two <p class="datetime">: the work's revision date in the
 * header, and the date you bookmarked it down in your own module. Taking the
 * first one for both is an easy mistake and produces a bookmark list that
 * sorts by the wrong thing entirely.
 */
function bookmarkInfo(li, bookmarkId) {
  const mine = li.match(/<div class="own user module group">([\s\S]*?)(?:<ul class="actions">|<\/div>)/i)?.[1] ?? '';
  const out = { bookmarkId };
  const when = mine.match(/<p class="datetime">([\s\S]*?)<\/p>/i);
  if (when) out.bookmarkedAt = htmlToText(when[1]);
  const notes = mine.match(/<blockquote class="userstuff">([\s\S]*?)<\/blockquote>/i);
  if (notes) out.bookmarkNotes = htmlToText(notes[1]) || null;
  const tagBlock = mine.match(/<ul class="meta tags commas">([\s\S]*?)<\/ul>/i)?.[1];
  if (tagBlock) out.bookmarkTags = tagsIn(tagBlock);
  /* Read from the blurb's own class attribute, not from anywhere in its
     markup: a tag link or a nested element mentioning "rec" would otherwise
     mark the bookmark as a recommendation. */
  const ownClasses = li.match(/^<li[^>]*\bclass="([^"]*)"/i)?.[1] ?? '';
  const classSet = new Set(ownClasses.split(/\s+/));
  out.bookmarkPrivate = classSet.has('private');
  out.bookmarkRec = classSet.has('rec');
  return out;
}

/**
 * History pages add a "last visited" line to each blurb. Absent everywhere
 * else, so the fields simply do not appear rather than arriving as nulls that
 * would overwrite good data on a later merge.
 */
function readingInfo(li) {
  const viewed = li.match(/<h4 class="viewed heading">([\s\S]*?)<\/h4>/i)?.[1];
  if (!viewed) return {};
  const text = htmlToText(viewed);
  const out = {};
  const last = text.match(/Last visited:\s*([0-9]{1,2} \w{3} \d{4})/i);
  if (last) out.lastVisited = last[1];
  const times = text.match(/Visited\s+(\d+)\s+times?/i);
  out.visits = times ? Number(times[1]) : 1;
  // AO3 says so explicitly when the copy you read is no longer the current one
  out.staleSinceVisit = /Latest version/i.test(text) ? false : /updated since/i.test(text);
  return out;
}

/** Total pages, so the crawler knows how far it has to walk. */
export function parsePagination(html) {
  const nav = html.match(/<ol[^>]*class="[^"]*pagination[^"]*"[\s\S]*?<\/ol>/i)?.[0];
  if (!nav) return { current: 1, total: 1 };
  const current = num(htmlToText(nav.match(/<li[^>]*class="[^"]*\bcurrent\b[^"]*"[^>]*>([\s\S]*?)<\/li>/i)?.[1] ?? '1')) || 1;
  const pages = [...nav.matchAll(/<a[^>]*href="[^"]*\bpage=(\d+)/gi)].map((m) => Number(m[1]));
  return { current, total: Math.max(current, ...pages, 1) };
}

export function parseListing(html) {
  return {
    works: splitBlurbs(html).map(parseBlurb).filter((w) => w.workId),
    pagination: parsePagination(html),
  };
}

/**
 * The contents of an element, counting nesting.
 *
 * A non-greedy /<div ...>([\s\S]*?)<\/div>/ stops at the first closing tag,
 * which is correct only for elements that contain no other divs. Work skins
 * nest constantly — a chat bubble sits inside a message body inside a chat
 * window — and that regex truncated a 2,000 word chapter to 17 words at the
 * first bubble. So the closing tag is found by counting depth.
 */
export function innerHtmlOf(html, openTagPattern) {
  const open = html.match(openTagPattern);
  if (!open) return null;
  const start = open.index + open[0].length;
  const tag = open[0].match(/^<([a-z0-9]+)/i)?.[1] ?? 'div';
  const scan = new RegExp(`<${tag}\\b[^>]*>|</${tag}\\s*>`, 'gi');
  scan.lastIndex = start;
  let depth = 1;
  let m;
  while ((m = scan.exec(html))) {
    depth += m[0][1] === '/' ? -1 : 1;
    if (depth === 0) return html.slice(start, m.index);
  }
  return html.slice(start);          // unbalanced markup: keep what there is
}

/* -------------------------------------------------------------- work page */

/**
 * The author's work skin.
 *
 * AO3 injects it between the #work-skin wrapper and the comment that marks
 * where the skin starts applying. Anchoring on that pair matters: the page
 * has other <style> blocks, and picking one of those up would apply site
 * chrome CSS to the story text.
 */
export function parseWorkSkin(html) {
  const start = html.search(/<div[^>]*id="work-skin"/i);
  if (start < 0) return null;
  const end = html.indexOf('BEGIN section where work skin applies', start);
  const region = html.slice(start, end < 0 ? start + 20000 : end);
  const css = [...region.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/gi)].map((m) => m[1].trim());
  return css.length ? css.join('\n') : null;
}

/** Every image the work points at, so they can be captured before they rot. */
export function imageUrls(html) {
  return [...new Set(
    [...html.matchAll(/<img\b[^>]*\bsrc="([^"]+)"/gi)]
      .map((m) => decodeEntities(m[1]))
      .filter((src) => /^https?:/i.test(src))
  )];
}

/**
 * The work's own metadata block, as the work page carries it.
 *
 * The same facts the EPUB preface gives, but from the source and current: a
 * work added by link has no EPUB behind it, so this is the only place its
 * rating, tags and stats come from.
 */
export function parseWorkMeta(html) {
  const block = innerHtmlOf(html, /<dl class="work meta group"[^>]*>/i) ?? '';
  const row = (cls) => {
    const at = block.search(new RegExp(`<dd class="${cls}[^"]*"[^>]*>`, 'i'));
    if (at < 0) return null;
    return innerHtmlOf(block.slice(at), new RegExp(`<dd class="${cls}[^"]*"[^>]*>`, 'i'));
  };
  const tagsOf = (cls) => tagsIn(row(cls) ?? '');

  const stats = row('stats') ?? '';
  const stat = (name) => htmlToText(
    stats.match(new RegExp(`<dd class="${name}"[^>]*>([\\s\\S]*?)</dd>`, 'i'))?.[1] ?? '') || null;

  const chapters = stat('chapters') ?? '';
  const [done, planned] = chapters.split('/');

  return {
    rating: tagsOf('rating')[0] ?? null,
    warnings: tagsOf('warning'),
    categories: tagsOf('category'),
    fandoms: tagsOf('fandom'),
    relationships: tagsOf('relationship'),
    characters: tagsOf('character'),
    freeform: tagsOf('freeform'),
    collections: tagsOf('collections'),
    language: htmlToText(row('language') ?? '') || null,
    published: stat('published'),
    // a finished work says Completed; one in progress says Updated
    updated: stat('status') ?? stat('published'),
    complete: /Completed/i.test(stats),
    words: num(stat('words')),
    chapters: num(done),
    chaptersPlanned: planned && planned.trim() !== '?' ? num(planned) : null,
    kudos: num(stat('kudos')),
    hits: num(stat('hits')),
    bookmarkCount: num(stat('bookmarks')),
  };
}

export function parseWorkPage(html, { workId = null } = {}) {
  const skin = html.match(/<div[^>]*id="workskin"[^>]*>([\s\S]*)$/i)?.[1] ?? html;

  const id = workId
    ?? html.match(/<li class="share[^"]*">[\s\S]{0,300}?\/works\/(\d+)/i)?.[1]
    ?? html.match(/\/works\/(\d+)\/chapters\/\d+/i)?.[1]
    ?? null;

  const title = htmlToText(skin.match(/<h2 class="title heading">([\s\S]*?)<\/h2>/i)?.[1] ?? '') || null;
  const authors = [...(skin.match(/<h3 class="byline heading">([\s\S]*?)<\/h3>/i)?.[1] ?? '')
    .matchAll(/<a[^>]*rel="author"[^>]*>([\s\S]*?)<\/a>/gi)].map((m) => htmlToText(m[1]));

  const body = skin.match(/<div[^>]*id="chapters"[^>]*>([\s\S]*)$/i)?.[1] ?? skin;
  /*
   * Each chapter is bounded by its own closing tag, found by counting depth.
   *
   * Splitting on "up to the next chapter div, or end of string" looks
   * equivalent and is not: the final chapter has no chapter after it, so it
   * absorbed everything to the end of the document — the kudos form, the
   * comment thread, the footer. That inflated it to 43KB and, because AO3
   * stamps a fresh CSRF token into that form on every request, made the last
   * chapter report a content change on every single sync.
   */
  let chapters = [];
  const chapterOpen = /<div class="chapter"[^>]*id="chapter-(\d+)"[^>]*>/gi;
  let open;
  while ((open = chapterOpen.exec(body))) {
    const inner = innerHtmlOf(body.slice(open.index), /<div class="chapter"[^>]*>/i) ?? '';
    chapters.push({
      number: Number(open[1]),
      title: htmlToText(inner.match(/<h3 class="title">([\s\S]*?)<\/h3>/i)?.[1] ?? '') || null,
      /*
       * Two views of the same chapter, deliberately.
       *
       * `block` is AO3's whole chapter: the title, the author's notes, the
       * "Chapter Text" landmark, the prose. Rendering that under AO3's own
       * stylesheet reproduces the page rather than approximating it.
       *
       * `html` is just the prose. Search indexes this one, so a phrase in an
       * author's note does not surface as if it were in the story.
       */
      block: inner,
      html: innerHtmlOf(inner, /<div class="userstuff module"[^>]*>/i)
        ?? innerHtmlOf(inner, /<div class="userstuff[^"]*"[^>]*>/i) ?? '',
    });
  }

  // a one-shot has no .chapter wrapper at all, just the userstuff block
  if (!chapters.length) {
    const only = innerHtmlOf(body, /<div class="userstuff"[^>]*>/i);
    if (only) chapters = [{ number: 1, title: null, html: only }];
  }

  return {
    workId: id,
    title,
    authors,
    summary: htmlToText(skin.match(/<div class="summary module">[\s\S]*?<blockquote[^>]*>([\s\S]*?)<\/blockquote>/i)?.[1] ?? '') || null,
    skinCss: parseWorkSkin(html),
    images: imageUrls(html),
    meta: parseWorkMeta(html),
    chapters,
  };
}

/**
 * The name the archive is currently greeting.
 *
 * The bookmark listing lives under a username, and the app has a session but
 * has never known whose. Rather than asking the reader to type a name the
 * archive already knows, it is read out of the page the session returns.
 */
/* Paths under /users/ that are pages rather than people. A signed-out header
   links to /users/login, and reading that as a username produced a sync that
   would have walked the bookmarks of somebody called "login". */
const NOT_A_USER = new Set(['login', 'logout', 'new', 'password', 'activate', 'search']);

export function signedInUser(html) {
  const text = String(html ?? '');
  const match = text.match(/<a[^>]+href="\/users\/([^/"?]+)"[^>]*>\s*(?:My )?Dashboard\s*<\/a>/i)
    ?? text.match(/id="greeting"[\s\S]{0,400}?href="\/users\/([^/"?]+)"/i);
  if (!match) return null;
  const name = decodeURIComponent(match[1]);
  return NOT_A_USER.has(name.toLowerCase()) ? null : name;
}
