/** The v3 folded folio. One set of shapes generates native and web assets. */
import { deflateSync } from 'node:zlib';
import { writeFileSync } from 'node:fs';

/* The canvas the adaptive icon is drawn on, so the two are the same picture. */
const CANVAS = 108;

const GROUND = [0x20, 0x27, 0x29];
const SHAPES = [
  { kind: 'polygon', points: [[31, 31], [43, 31], [43, 69], [31, 77]], colour: [0xe7, 0x9a, 0x80], alpha: 1 },
  { kind: 'polygon', points: [[47, 31], [78, 31], [69, 44], [47, 44]], colour: [0xff, 0xf3, 0xdd], alpha: 1 },
  { kind: 'polygon', points: [[47, 49], [67, 49], [58, 62], [47, 62]], colour: [0xe7, 0x9a, 0x80], alpha: 1 },
];
const hex = (colour) => '#' + colour.map(c => c.toString(16).padStart(2, '0')).join('');
const path = (shape) => shape.points.map(([x, y], i) => `${i ? 'L' : 'M'}${x},${y}`).join(' ') + ' Z';
writeFileSync(new URL('../android/res/drawable/ic_launcher_foreground.xml', import.meta.url),
  `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/make-icon.mjs. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">
${SHAPES.map(s => `    <path android:pathData="${path(s)}" android:fillColor="${hex(s.colour)}" />`).join('\n')}
</vector>
`);
writeFileSync(new URL('../android/res/values/ic_launcher_background.xml', import.meta.url),
  `<?xml version="1.0" encoding="utf-8"?>
<resources><color name="ic_launcher_background">${hex(GROUND)}</color></resources>
`);
writeFileSync(new URL('../app/folio-mark.svg', import.meta.url),
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108"><rect width="108" height="108" rx="24" fill="${hex(GROUND)}"/>${SHAPES.map(s => `<path d="${path(s)}" fill="${hex(s.colour)}"/>`).join('')}</svg>\n`);

/** Is this point inside the shape, in canvas units? */
function covers(shape, px, py) {
  let x = px;
  let y = py;
  if (shape.turn) {
    /* Turned about the pivot, so the test asks the untumed shape about a
       turned point rather than the other way round. */
    const a = (-shape.turn * Math.PI) / 180;
    const [cx, cy] = shape.pivot;
    const dx = px - cx;
    const dy = py - cy;
    x = cx + dx * Math.cos(a) - dy * Math.sin(a);
    y = cy + dx * Math.sin(a) + dy * Math.cos(a);
  }

  if (shape.kind === 'rect' || shape.kind === 'roundRect') {
    const { x: rx, y: ry, w, h } = shape;
    if (x < rx || x > rx + w || y < ry || y > ry + h) return false;
    const r = shape.r ?? 0;
    if (!r) return true;
    // only the corners can be outside a rounded rectangle
    const nx = x < rx + r ? rx + r : (x > rx + w - r ? rx + w - r : x);
    const ny = y < ry + r ? ry + r : (y > ry + h - r ? ry + h - r : y);
    return (x - nx) ** 2 + (y - ny) ** 2 <= r * r;
  }

  // a polygon, by the even-odd rule
  const pts = shape.points;
  let inside = false;
  for (let i = 0, j = pts.length - 1; i < pts.length; j = i++) {
    const [xi, yi] = pts[i];
    const [xj, yj] = pts[j];
    if ((yi > y) !== (yj > y)
      && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
}

/**
 * Four samples across and four down per pixel.
 *
 * An icon is mostly edges — three turned pages and a notched ribbon — and at
 * 48 pixels an unsampled edge is a staircase. Sixteen samples is enough that
 * the stairs disappear and cheap enough that five sizes render instantly.
 */
const GRID = 4;

function draw(size, { round = false } = {}) {
  const px = new Uint8Array(size * size * 3);
  const scale = CANVAS / size;
  const mid = (size - 1) / 2;
  const radius = size / 2;

  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      let [r, g, b] = GROUND;

      for (const shape of SHAPES) {
        let hits = 0;
        for (let sy = 0; sy < GRID; sy++) {
          for (let sx = 0; sx < GRID; sx++) {
            const cx = (x + (sx + 0.5) / GRID) * scale;
            const cy = (y + (sy + 0.5) / GRID) * scale;
            if (covers(shape, cx, cy)) hits++;
          }
        }
        if (!hits) continue;
        const a = (hits / (GRID * GRID)) * shape.alpha;
        r = Math.round(r * (1 - a) + shape.colour[0] * a);
        g = Math.round(g * (1 - a) + shape.colour[1] * a);
        b = Math.round(b * (1 - a) + shape.colour[2] * a);
      }

      /* The round variant is clipped rather than drawn differently, so the
         two cannot come out as different pictures. */
      if (round) {
        const d = Math.hypot(x - mid, y - mid);
        if (d > radius) { r = 0; g = 0; b = 0; }
      }

      const at = (y * size + x) * 3;
      px[at] = r;
      px[at + 1] = g;
      px[at + 2] = b;
    }
  }
  return px;
}

/* --------------------------------------------------------------- the file */

const crcTable = Array.from({ length: 256 }, (_, n) => {
  let c = n;
  for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  return c >>> 0;
});

function crc32(bytes) {
  let c = 0xffffffff;
  for (const byte of bytes) c = crcTable[(c ^ byte) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function chunk(type, body) {
  const head = Buffer.alloc(8);
  head.writeUInt32BE(body.length, 0);
  head.write(type, 4, 'ascii');
  const tail = Buffer.alloc(4);
  tail.writeUInt32BE(crc32(Buffer.concat([head.subarray(4), body])), 0);
  return Buffer.concat([head, body, tail]);
}

function png(size, px) {
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(size, 0);
  ihdr.writeUInt32BE(size, 4);
  ihdr[8] = 8;    // eight bits a channel
  ihdr[9] = 2;    // colour, no alpha: the ground is opaque
  const stride = size * 3;
  const raw = Buffer.alloc((stride + 1) * size);
  for (let y = 0; y < size; y++) {
    raw[y * (stride + 1)] = 0;   // no filter; these compress well enough flat
    Buffer.from(px.subarray(y * stride, (y + 1) * stride))
      .copy(raw, y * (stride + 1) + 1);
  }
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

/** What each density actually asks for, rather than one size copied five ways. */
const DENSITIES = {
  mdpi: 48,
  hdpi: 72,
  xhdpi: 96,
  xxhdpi: 144,
  xxxhdpi: 192,
};

let wrote = 0;
for (const [density, size] of Object.entries(DENSITIES)) {
  for (const [name, round] of [['ic_launcher', false], ['ic_launcher_round', true]]) {
    const at = new URL(`../android/res/mipmap-${density}/${name}.png`, import.meta.url);
    writeFileSync(at, png(size, draw(size, { round })));
    wrote++;
  }
}
process.stdout.write(`wrote ${wrote} icons\n`);
